import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";

import QueryProvider from "./providers";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  weight: [ "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Tesfa",
  description: "Generated by create next app",
 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${josefinSans.variable}`}>
       <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body >
        <QueryProvider>
          <main >{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}


