import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";
import Sidebar from "./sharedComponents/SideBar";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin-sans",
  weight: [ "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Tesfa",
  description: "Generated by create next app",
  icons: {
    icon: "/Images/TesfaLogo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${ josefinSans.variable}`}>
      <body
        className={`${ josefinSans.variable}`}
      >
        <main >{children}</main>
    
      </body>
    </html>
  );
}
